### PR TITLE
update from correct 1.5.0

### PR DESCRIPTION
**Pull request by zemiacsik**
I have updated correct latest 1.5.0 version with PHP 7.2 support. I am sorry for messing around.

### CODE REVIEW

**Comment by zemiacsik** [comment]
The thing is I previously went from "1.2" branch because it was SS3, but I have not looked at tags so I had updated out dated version and then 1.5.1 and 1.6.0 did not work.

**Comment by bummzack** [comment]
You're basing your work on `master`, which is the SS4 version. 
To me it looks like your changes were merged and tagged properly, there's no need for this PR.

**Comment by zemiacsik** [comment]
Sorry, I am kinda lost here.
Yes, they were merged and tagged properly but they are from wrong version.. if you look at 1.5.0 and 1.5.1 they are different (so 1.5.1 and 1.6.0 do not work).
It would be more clearer for me if SS3 has its own up to date branch and not a tag on master.

Or should I switch to "1.2" branch, then change tag to 1.5.0, make changes and pull?

**Comment by bummzack** [comment]
Let me explain: `1.5.0` was the latest release before your PR. Then `1.5.1` was tagged… it contains your PR and is the latest version for SilverStripe 3.x. Then there was also a release being tagged as `1.6.0`, which is for SilverStripe 3.7+

Both these releases should be compatible with PHP 7.2

**Comment by zemiacsik** [comment]
I understand this, but my PR does not come from 1.5.0 (I had not noticed this before).. try to look at them and you will see different files:
1.5.1 4 years ago:

**Comment by bummzack** [comment]
You don't base a PR on a tag, but on a branch. While the `1.2` branch name is a bit misleading, it was the correct branch for you to use.

Not sure why github shows some folders to be older in the 1.5.1 tree, but that's probably not a metric you can count on. You should compare the versions like this:
Changes from 1.5.0 to 1.5.1: https://github.com/unclecheese/silverstripe-display-logic/compare/1.5.0...1.5.1
Changes from 1.5.0 to 1.6.0: https://github.com/unclecheese/silverstripe-display-logic/compare/1.5.0...1.6.0

It's all as it should be.

**Comment by zemiacsik** [comment]
And that is a problem, because I used "1.2" branch which is probably the same as 1.2 tag so is out dated from 1.5.0 version and after my PR the 1.5.1 seems to be 1.2 with my changes so basicaly it went back (you see it when you compare them).
I noticed this just after composer update and I have realized my mistake.

**Comment by bummzack** [comment]
No, as I said. A branch is **not** a tag. The `1.5.0` version is a tag on the `1.2` branch. There's nothing wrong here.

The `1.5.1` and `1.6.0` tags are also on the `1.2` branch… thus if you compare the `1.2` branch, with `1.6.0` there isn't any difference: https://github.com/unclecheese/silverstripe-display-logic/compare/1.2...1.6.0

**Comment by zemiacsik** [comment]
Hmm ok, I have definitely some homework here, although if you look at them closely you will see the difference and thus 1.5.0 is working one (because is latest and 1.5.1 nor 1.6.0 do not come from it, as I said).

**Comment by bummzack** [comment]
I just looked at the history graph, and you're right. The SS4 upgrade happened right after the `1.5.0` tag and **both** were on the master branch. 
What should have been done is a separate branch for 1 at the point of `1.5.0` or merge `1.5.0` into `1.2`. I guess that can still be done, I'll leave that to @unclecheese. Otherwise quite some changes will be lost. I really don't know why they don't show up when you compare `1.5.0` to `1.5.1`, but they do if you compare `1.2` to `1.5.0`: https://github.com/unclecheese/silverstripe-display-logic/compare/1.2...1.5.0

**Pull request closed without merging**
