### PR TITLE
SS4 upgrade.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
SilverStripe 4 upgrade.

### CODE REVIEW

**Comment by unclecheese** [comment]
Nice stuff, Mojmir. Will have a look at this soon.

**Comment by mfendeksilverstripe** [comment]
@unclecheese I found some issues, it's WIP.

**Comment by mfendeksilverstripe** [comment]
@unclecheese Issues are resolved now.

**Comment by fonsekaean** [comment]
Hello @mfendeksilverstripe @unclecheese I didnt notice this MR and I did a ss4 upgrade here too. 

https://github.com/unclecheese/silverstripe-display-logic/pull/83

In that I included some unit tests etc. May be you can use them. 

Also two important things I want to point out are:

1. when using the dataobject decorator to hold the DisplayLogicCriteria `protected $displayLogicCriteria = [];` it use this globally for all the input fields. EG: if you have 2 display logic conditions in one form, only the second one gets populated and all the fields gets that. 

I used `$this->owner` to store the Criteria options. 

2. I added yarn configs, and webpack and wrote the JS to work in compatible with the current codes. The code which was there didnt have any effect on the dropdowns and I suspect thats the case on this branch too. 

Let me know some thoughts. My merge request is here. 

https://github.com/unclecheese/silverstripe-display-logic/pull/83

Cheers

**Comment by mfendeksilverstripe** [comment]
Hi @fonsekaean I had a look at your code and here is my feedback:

1 - I'm aware of the possibility of pushing the data to the owner, but I don't think that's the best solution because you're making the extension specific data available on the owner. My solution keeps the data protected in the extension. Note that I changed the protected data to an array which functions as a key-value storage, so the data for each field is stored separately, thus preventing any conflicts.

2 - I like your JS code and I think it's an improvement over my version. I would be happy to include that.

I'm also happy to include your unit tests.

@unclecheese I currently don't have more time to work on this, so I'm not sure when can I get back to this. Feel free to merge the two pull requests as appropriate.

**Comment by unclecheese** [comment]
Thanks to both of you. I agree with @mfendeksilverstripe on the extension properties. It doesn't make sense to push that data to the owner. I think a registry approach makes more sense.

Really happy to see unit tests included. Would love to get behat tests in, as well, as this module is very UI focused.

I had big ideas to [redesign the API](https://github.com/unclecheese/silverstripe-display-logic/issues/67#issuecomment-244820215) of this module a while back to be much more explicit, and I saw the upgrade as an opportunity to do that, but I think the top priority right now is to get this module SS4 compatible and focus on refactoring later.

Overall, there's a happy solution between these two PRs that I'll be sorting through shortly. Thanks again for your efforts.

**Comment by madmatt** [comment]
Hey @unclecheese,

Is there any update on this? I'm keen to know if there are still plans afoot to upgrade this to SS4 or not :)

Thanks!

**Comment by gorriecoe** [comment]
Hey @madmatt,  master is currently ss4 compatible after PR #86.

**Comment by unclecheese** [comment]
@madmatt @gorriecoe That's correct. Master is SS4. I haven't tagged a release yet because the tests are failing. If anyone can pitch in on that, I'd love the help.

I'll tag a release now, though, since it's more important to get this out than have perfect CI.

Thanks for your patience, everyone.

**Comment by madmatt** [comment]
Oh awesome, thanks @gorriecoe and @unclecheese - I had missed that PR!

**Comment by unclecheese** [comment]
Tagged 2.0.0. Thanks, everyone.



On Mon, Feb 26, 2018 at 17:36, Matt Peel <notifications@github.com> wrote:
Oh awesome, thanks @gorriecoe [https://github.com/gorriecoe] and @unclecheese [https://github.com/unclecheese] - I had missed that PR!

**Comment by michalkleiner** [comment]
Should this be closed when SS4 version is out?

**Pull request closed without merging**
