### PR TITLE
Add silverstripe 4 Support

### PR DESCRIPTION
**Pull request by fred0r007**
Add silverstripe 4 Support

### CODE REVIEW

**Comment by unclecheese** [comment]
Whoa. Nice PR, mate. Will review.

**Comment by Zauberfisch** [comment]
Should we perhaps consider renaming classes in the process of introducing namespaces?

Now that the module has namespaces, there is no need to prefix each class with DisplayLogic. So I would like to see the class `DisplayLogicCriteria` (`UncleCheese\DisplayLogic\DisplayLogicCriteria`) renamed to `Criteria` (`UncleCheese\DisplayLogic\Criteria`) because we alreadt have DisplayLogic in the namespace.

**Comment by unclecheese** [comment]
Yeah, I agree with @Zauberfisch. I've been trying to use more generic class names in my SS4 projects, provided it's not too ambiguous (i.e. "Wrapper"). Suggest:

* `UncleCheese\DisplayLogic\Criteria`
* `UncleCheese\DisplayLogic\Criterion`
* `UncleCheese\DisplayLogic\FormFieldExtension`
* `UncleCheese\DisplayLogic\DisplayLogicWrapper`

A couple other comments:

* Can we move the `code/` folder to `src/` to be more consistent with modern libraries?
* Can we add PSR-4 autoloading to the `composer.json` file?
* Apply PSR-2 formatting to comply with SS4 standards?

**Comment by Zauberfisch** [comment]
I actually think even Wrapper is acceptable. It's namespaced anyway.

And if someone has 2 wrappers or is afraid of confusing himself, it's always possible to do `use UncleCheese\DisplayLogic\Wrapper as DisplayLogicWrapper;`

Regarding the `src/` folder, I am unsure on this subject, I will wait and see what official SS modules do.
On the other points, yes.

**Comment by unclecheese** [comment]
I guess it's a matter of preference, but to me the class name should give at least some indication of what it does. `Criteria` infers logic. `Wrapper` just infers placement.  If I'm trying to make sense of a block of code and I see `Wrapper::create(...)` I couldn't even guess what that might be for. I'd be in favour of something just a bit more semantically relevant -- even `DisplayLogic::create()` would be a good replacement for `DisplayLogicWrapper` to me.

As for `code/`, that is is for all intents and purposes deprecated. Most SS modules, including those in the SS core, are moving toward `src/`.

**Comment by Zauberfisch** [comment]
Well, to me DisplayLogicWrapper does not imply anything that Wrapper doesn't. It's a wrapper, of what is not clear.
Or on the other Example, Criteria implies that it's a criteria, but it could be any kind of criteria, so in some other class, when you write `new Criteria()` it's as confusing as `new Wrapper()`, because it could just as well be a criteria object used for, I don't know, maybe routing decisions of `Director` or `Controller` or what ever.

So if someone needs a prefix in his code for the classes used, then one shall use `use X as prefixX;`

So my personal preference is to remove the prefix on all classes. But if not, then we might as well keep it on all of them and keep it at least consistent.
(If we really have a problem with the word wrapper, it could be renamed to `UncleCheese\DisplayLogic\FormFieldWrapper` maybe?)

**Comment by colintucker** [comment]
Adding my two cents, since this is a great module and I'm really keen to use it in SS4... 😉 sorry @unclecheese I tend to agree with @Zauberfisch, having `DisplayLogic` in both the namespace path and the class name seems redundant.

However, I will concede that just having a class called `Wrapper` seems too generic when defining the form code.  I like @Zauberfisch 's suggestion of `FormFieldWrapper`. 👍 

I also agree that `code/` should become `src/` for the SS4 version of the module, with the following PSR-4 autoload config added to the `composer.json`:

```json
"autoload": {
  "psr-4": {
    "UncleCheese\\DisplayLogic\\": "src/"
  }
}
```

What do you think?

**Comment by unclecheese** [comment]
Yeah, I've done a lot of SS4 work since I reviewed this PR, and @Zauberfisch is right. Simple names are best. Can always alias them.

**Comment by ec8or** [comment]
Just tried this and seems like the way DropdownFields are now generated changes aren't being picked up. Had to add a new entwine to fix it but probable a better way:
```
	$('div.display-logic-master .active-result').entwine({
		onclick: function() {
			this.closest(".display-logic-master").notify();
		}
	});
```

**Comment by ec8or** [comment]
Also seems like the Javascript isn't loaded if you navigate to a record from a GridField. Have to refresh trhe page to make the logic work.

**Comment by adrexia** [comment]
I've fixed up some of the deprecations, and made the naming changes discussed.  https://github.com/adrexia/silverstripe-display-logic/commit/8a47e81b4cde803139d1df08592c71ff33f38b2b

I couldn't track down why the js only works on hard refresh though. It also fails after saving/publishing an object. Anyone have more insight into that issue?

**Pull request closed without merging**
