### PR TITLE
added support for PHP 7.2

### PR DESCRIPTION
**Pull request by zemiacsik**

### CODE REVIEW

**Comment by unclecheese** [comment]
Thanks, but just curious..  why not just bump the version requirement to 3.7?

**Comment by bummzack** [comment]
You still need to extend from `SS_Object`, and not `Object`.

**Comment by zemiacsik** [comment]
I thought 3.7 would not need to be mandatory so it could be used also with lower versions or..?

**Comment by unclecheese** [comment]
Right, but the `class_alias()` is for < 3.7 compatibility, and that just seem like unnecessary hackery to me. If you want PHP 7.2, you're already compelled to use SS >= 3.7, so why not display-logic >= 1.5?

tl;dr Bump composer to 3.7, remove the `class_alias()`, and tag 1.5.

**Comment by bummzack** [comment]
He's just following official release notes/recommendations: https://docs.silverstripe.org/en/3/changelogs/3.7.0/#for-module-authors

**Comment by unclecheese** [comment]
Oh, right, those. :)

Alright, we'll do two commits, then. We'll merge this on to 1.4.x, and then a separate commit that removes the `class_alias()` and bumps the framework requirement on 1.5.x.

**Comment by zemiacsik** [comment]
@unclecheese There is an issue.. I had not checked tags and I only looked at SS3 branch, so if you look at 1.5.0 then 1.5.1 is not quite coming out from it. I am sorry, I am not much experienced with github yet. but is here something I can do to fix this?

**Pull request merged**
